server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/test
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  data:
    redis:
      host: localhost
      port: 6379
      password: password

  mail:
    host: ${MAIL_HOST}
    port: ${MAIL_PORT}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connection-timeout: 5000
          timeout: 5000
          write-timeout: 5000

jwt:
  secret: testestesttestestesttestestesttestestesttestestesttestestesttestestesttestestesttestestest
  access-expiration: 6000
  refresh-expiration: 12000

minio:
  endpoint: http://localhost:9000
  accessKey: aUhlqcifrjWPF6GG1Hp2
  secretKey: G7QqiGFYJoUbEJ2BhtdaozHEctwaEf9tyXKWRPed
  bucketName: test
