format_version: 10

pipelines:
  mandamong-monolithic-ci:
    group: defaultGroup
    environment: mandamong-monolithic
    materials:
      mandamong:
        git: https://github.com/mandamong/kotlin-spring-mandamong
        username: digitpic
        shallow_clone: false
        auto_update: true
        branch: develop
        encrypted_password: AES:UgHmpe2xcIyYJnHgtiQw3Q==:idjEfTlzt/4IFEoT/yHQkBjord7bPIowJY/jV6sfFXk50m31BUBbiYHdDL4+j+oX

    stages:
      - build:
          jobs:
            build:
              tasks:
                - exec:
                    command: mkdir
                    arguments: ["-p", "src/main/resources", "src/test/resources"]
                    run_if: passed

                - exec:
                    command: bash
                    arguments: ["-c", "echo" "$APPLICATION" ">" "application.yml"]
                    run_if: passed

                - exec:
                    command: cp
                    arguments: ["application.yml", "src/main/resources/application.yml"]
                    run_if: passed

                - exec:
                    command: cp
                    arguments: ["application.yml", "src/test/resources/application.yml"]
                    run_if: passed

                - exec:
                    command: chmod
                    arguments: ["+x", "./gradlew"]
                    run_if: passed

                - exec:
                    command: ./gradlew
                    arguments: ["clean", "build"]
                    run_if: passed

                - exec:
                    command: docker
                    arguments: ["login", "-u", "$DOCKER_USER", "-p", "$DOCKER_PASSWORD"]
                    run_if: passed

                - exec:
                    command: docker
                    arguments:
                      [
                        "buildx", "build",
                        "-t", "$DOCKER_USER/$DOCKER_IMAGE:latest",
                        "--platform", "linux/amd64,linux/arm64",
                        "--push", "."
                      ]
                    run_if: passed

  mandamong-monolithic-cd:
    group: defaultGroup
    materials:
      mandamong:
        git: https://github.com/mandamong/kotlin-spring-mandamong
        username: digitpic
        shallow_clone: false
        auto_update: true
        branch: develop
        encrypted_password: AES:UgHmpe2xcIyYJnHgtiQw3Q==:idjEfTlzt/4IFEoT/yHQkBjord7bPIowJY/jV6sfFXk50m31BUBbiYHdDL4+j+oX

      mandamong-monolithic-build:
        pipeline: mandamong-monolithic-ci
        stage: build

    stages:
      - deploy:
          jobs:
            deploy:
              tasks:
                - exec:
                    command: mkdir
                    arguments: ["-p", "$HOME/.ssh"]
                    run_if: passed

                - exec:
                    command: bash
                    arguments: ["-c", "echo \"$SSH_PRIVATE_KEY\" > $HOME/.ssh/id_rsa"]
                    run_if: passed

                - exec:
                    command: chmod
                    arguments: ["600", "$HOME/.ssh/id_rsa"]
                    run_if: passed

                - exec:
                    command: ssh
                    arguments:
                      [
                        "-o", "StrictHostKeyChecking=no",
                        "-p", "$SSH_PORT",
                        "$SSH_USER@$SSH_HOST",
                        "sudo kubectl rollout restart deployment mandamong-deployment -n mandamong && sudo kubectl rollout status deployment mandamong-deployment -n mandamong"
                      ]
                    run_if: passed
